server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yunda_fault?characterEncoding=utf8&useUnicode=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      connection-timeout: 30000
      minimum-idle: 10
      idle-timeout: 600000
      connection-test-query: SELECT 1
      validation-timeout: 60000
      max-lifetime: 1800000
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl