spring:
    # 环境 cn|stg|prd
    profiles:
        active: local
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
        default-property-inclusion: non_null
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true